apiVersion: apps/v1
kind: Deployment
metadata:
  name: minha-app-repo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minha-app-repo
  template:
    metadata:
      labels:
        app: minha-app-repo
    spec:
      containers:
      - name: minha-app-repo
        image: 782622073147.dkr.ecr.us-east-1.amazonaws.com/minha-app-repo:latest
        ports:
        - containerPort: 5000
